// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アカウントの提供元。カードの見出しと、サービスをオンにするときに求める認証を決める。
 */
export type AccountProvider = "google" | "icloud" | "imap";
