// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountProvider } from "./AccountProvider";

/**
 * 設定の「アカウント」のカード 1 枚（アドレスごと）。
 *
 * 中身（メール・Google 連携）はそれぞれの一覧（`AccountSummary` / `GoogleAccount`）にあり、
 * ここはその id で指すだけ。画面はこの id で突き合わせてカードを組む。
 */
export type AccountProfile = { id: number, provider: AccountProvider, email: string, 
/**
 * 利用者が付けた呼び名。None ならアドレスで出す。
 */
display_name: string | null, 
/**
 * このアドレスのメールアカウント（`accounts.id`）。メールを使わないなら空。
 * 同じアドレスの重複登録（以前は拒んでいなかった）があれば複数になる。
 */
mail_account_ids: Array<number>, 
/**
 * このアドレスの Google 連携（`google_accounts.id`）。連携していなければ None。
 */
google_account_id: number | null, };
