// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アカウント一覧表示用（資格情報は含めない）。
 */
export type AccountSummary = { id: number, email: string, display_name: string | null, imap_host: string, smtp_host: string, sync_window: string, unread_count: number, total_count: number, };
