// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountProvider } from "./AccountProvider";

/**
 * アカウント追加の入力（フロントから受け取る）。
 */
export type AccountInput = { email: string, display_name: string | null, 
/**
 * ログイン用サーバーユーザー名（メールアドレスと別にできる）。未指定なら email を使う。
 */
username: string | null, imap_host: string, imap_port: number, smtp_host: string, smtp_port: number, 
/**
 * 追加の流れで選んだ提供元（カードの見出し）。None ならアドレスとサーバーから推し量る。
 */
provider: AccountProvider | null, };
