// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 境界型の例。ts-rs により `src/bindings/AppInfo.ts` を生成する。
 * 生成: `npm run gen:bindings`（= cargo test --lib export_bindings）
 */
export type AppInfo = { name: string, version: string, identifier: string, };
