// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 添付候補ファイルのメタ情報（作成画面の一覧表示・事前検証用）。
 */
export type AttachmentMeta = { 
/**
 * 元のファイルパス（送信時に Rust が読み込むキー）。
 */
path: string, 
/**
 * 表示名（パスの basename）。
 */
name: string, 
/**
 * バイト数。
 */
size: bigint, };
