// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 添付ファイル（一覧/ダウンロード状態）。
 * `is_downloaded` が false のときは本体未取得（メタのみ）。
 */
export type AttachmentSummary = { id: number, filename: string, content_type: string | null, size: number, is_downloaded: boolean, 
/**
 * ダウンロード済みの保存先（未取得なら None）。
 */
file_path: string | null, };
