// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ゲスト設定の入力（保存時に一括で置き換える）。
 */
export type AttendeeInput = { contact_id: number | null, email: string | null, name: string | null, response: string | null, };
