// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * プロバイダ自動判定の結果（docs/ONBOARDING.md）。
 */
export type AutoconfigResult = { email: string, display_name: string | null, imap_host: string, imap_port: number, imap_security: string, smtp_host: string, smtp_port: number, smtp_security: string, source: string, note: string | null, };
