// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * カレンダー（マイ/他）。docs/DATABASE_SCHEMA.md（calendars）。
 */
export type CalendarSummary = { id: number, 
/**
 * 表示名（空なら UI で既定名を表示）。
 */
name: string, color: string | null, 
/**
 * 'mine'（自分の）| 'other'（他の/購読）。
 */
kind: string, 
/**
 * 表示オン/オフ。
 */
visible: boolean, 
/**
 * 既定カレンダー（新規予定の初期。削除不可）。
 */
is_default: boolean, sort_order: number, 
/**
 * 由来。'local' | 'ics' | 'google' | 'caldav'。UI のプロバイダー分け・ロゴ表示に使う。
 */
source: string, 
/**
 * Google 連携カレンダーの場合の連携アカウント（メール）。ローカルは None。
 */
account_email: string | null, 
/**
 * Google の権限。'owner' | 'writer' | 'reader' | 'freeBusyReader'。書き込み可否の表示に使う。
 * ローカルカレンダーは None（暗黙的に編集可）。
 */
access_role: string | null, };
