// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * カレンダーの作成・更新入力。`id` が None なら新規作成。
 */
export type CalendarInput = { id: number | null, name: string, color: string | null, kind: string | null, };
