// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactAddress } from "./ContactAddress";
import type { ContactCustomField } from "./ContactCustomField";
import type { ContactDate } from "./ContactDate";
import type { ContactHandle } from "./ContactHandle";
import type { ContactOrganization } from "./ContactOrganization";
import type { ContactRelation } from "./ContactRelation";
import type { ContactUrl } from "./ContactUrl";
import type { ContactValue } from "./ContactValue";

/**
 * 連絡先の作成・更新入力（フロントから受け取る）。`id` が None なら新規作成。
 *
 * 配列・タグは**送ったもので置き換える**。画面が扱わない項目も、読み込んだ連絡先の値を
 * そのまま入れて送れば保たれる（[`ContactSummary`] と同じ [`ContactFields`] を持つため）。
 */
export type ContactInput = { id: number | null, 
/**
 * 表示名（vCard の FN）。
 */
display_name: string, 
/**
 * 敬称（N の 4 番目 / Google の honorificPrefix）。
 */
name_prefix: string | null, 
/**
 * 姓。
 */
family_name: string | null, 
/**
 * ミドルネーム。
 */
middle_name: string | null, 
/**
 * 名。
 */
given_name: string | null, 
/**
 * 接尾辞（N の 5 番目 / Google の honorificSuffix）。
 */
name_suffix: string | null, 
/**
 * よみ（姓）。
 */
phonetic_family: string | null, 
/**
 * よみ（ミドル）。
 */
phonetic_middle: string | null, 
/**
 * よみ（名）。
 */
phonetic_given: string | null, 
/**
 * ニックネーム。
 */
nickname: string | null, 
/**
 * 旧姓（iCloud のみ）。
 */
maiden_name: string | null, 
/**
 * 誕生日（`YYYY-MM-DD` / 年なし `--MM-DD`）。
 */
birthday: string | null, note: string | null, 
/**
 * 会社として表示する（iCloud の X-ABShowAs:COMPANY）。
 */
show_as_company: boolean, 
/**
 * お気に入り（Google の「スター付き」と同期）。
 */
is_favorite: boolean, 
/**
 * 取引先の手動フラグ（Rondine 固有。docs/FILTERING.md）。
 */
is_business: boolean, 
/**
 * この相手からのメールで外部画像を許可（Rondine 固有。docs/MAIL_SECURITY.md）。
 */
allow_remote_images: boolean, organizations: Array<ContactOrganization>, emails: Array<ContactValue>, phones: Array<ContactValue>, addresses: Array<ContactAddress>, urls: Array<ContactUrl>, dates: Array<ContactDate>, relations: Array<ContactRelation>, handles: Array<ContactHandle>, custom_fields: Array<ContactCustomField>, 
/**
 * タグ（メールと共通の tags。Google のラベル / vCard の CATEGORIES）。
 */
tags: Array<string>, };
