// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactAddress } from "./ContactAddress";
import type { ContactCustomField } from "./ContactCustomField";
import type { ContactDate } from "./ContactDate";
import type { ContactHandle } from "./ContactHandle";
import type { ContactLink } from "./ContactLink";
import type { ContactOrganization } from "./ContactOrganization";
import type { ContactRelation } from "./ContactRelation";
import type { ContactUrl } from "./ContactUrl";
import type { ContactValue } from "./ContactValue";

/**
 * 連絡先（一覧・詳細で共通）。
 */
export type ContactSummary = { id: number, 
/**
 * 端末をまたいで同じ人を指す ID（UUID v4・小文字ハイフン区切り）。行の `id` は DB の中だけの
 * 番号で、入れ直しや書き出し/取り込みで変わる。統合では残る側の uid を使う（マイグレーション
 * 0064・docs/CONTACT_MODEL.md §1-1）。
 */
uid: string, 
/**
 * 並び替え用（よみ優先。保存時に組み立てる）。
 */
sort_name: string | null, 
/**
 * アバター画像のパス（同期は後続）。
 */
avatar_path: string | null, 
/**
 * 論理削除（ゴミ箱）の日時（UTC 文字列）。非 null＝削除済み。
 */
deleted_at: string | null, 
/**
 * 主メール（`contact_emails` の position = 0 の写し。一覧用）。
 */
primary_email: string | null, 
/**
 * 主電話（同上）。
 */
primary_phone: string | null, 
/**
 * 主の会社名（`contact_organizations` の position = 0 の写し。一覧用）。
 */
primary_organization: string | null, 
/**
 * つながっているサービス（無ければ Rondine のみ）。一覧でも充填する。
 */
links: Array<ContactLink>, 
/**
 * 表示名（vCard の FN）。
 */
display_name: string, 
/**
 * 敬称（N の 4 番目 / Google の honorificPrefix）。
 */
name_prefix: string | null, 
/**
 * 姓。
 */
family_name: string | null, 
/**
 * ミドルネーム。
 */
middle_name: string | null, 
/**
 * 名。
 */
given_name: string | null, 
/**
 * 接尾辞（N の 5 番目 / Google の honorificSuffix）。
 */
name_suffix: string | null, 
/**
 * よみ（姓）。
 */
phonetic_family: string | null, 
/**
 * よみ（ミドル）。
 */
phonetic_middle: string | null, 
/**
 * よみ（名）。
 */
phonetic_given: string | null, 
/**
 * ニックネーム。
 */
nickname: string | null, 
/**
 * 旧姓（iCloud のみ）。
 */
maiden_name: string | null, 
/**
 * 誕生日（`YYYY-MM-DD` / 年なし `--MM-DD`）。
 */
birthday: string | null, note: string | null, 
/**
 * 会社として表示する（iCloud の X-ABShowAs:COMPANY）。
 */
show_as_company: boolean, 
/**
 * お気に入り（Google の「スター付き」と同期）。
 */
is_favorite: boolean, 
/**
 * 取引先の手動フラグ（Rondine 固有。docs/FILTERING.md）。
 */
is_business: boolean, 
/**
 * この相手からのメールで外部画像を許可（Rondine 固有。docs/MAIL_SECURITY.md）。
 */
allow_remote_images: boolean, organizations: Array<ContactOrganization>, emails: Array<ContactValue>, phones: Array<ContactValue>, addresses: Array<ContactAddress>, urls: Array<ContactUrl>, dates: Array<ContactDate>, relations: Array<ContactRelation>, handles: Array<ContactHandle>, custom_fields: Array<ContactCustomField>, 
/**
 * タグ（メールと共通の tags。Google のラベル / vCard の CATEGORIES）。
 */
tags: Array<string>, };
