// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 連絡先の書き出し結果。
 */
export type ContactExportReport = { 
/**
 * 書き出した人数。
 */
exported: number, };
