// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 関係（配偶者・子・上司など）。
 */
export type ContactRelation = { label: string | null, name: string, };
