// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * つながりの状態。
 */
export type ContactLinkState = "synced" | "pending_create" | "pending_delete";
