// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 所属する会社（複数可。先頭が主）。組織カードにつながっていれば `org_id` を持つ。
 */
export type ContactOrganization = { 
/**
 * つながっている組織カード。None＝カードにつながっていない（会社名だけ）。
 */
org_id: number | null, 
/**
 * 会社名（カードにつながっていればカードの名前と同期した写し）。
 */
name: string | null, 
/**
 * 会社名のよみ。
 */
phonetic_name: string | null, 
/**
 * 役職。
 */
title: string | null, 
/**
 * 部署。
 */
department: string | null, };
