// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactAddressInput } from "./ContactAddressInput";
import type { ContactValueInput } from "./ContactValueInput";

/**
 * 連絡先の作成・更新入力（フロントから受け取る）。`id` が None なら新規作成。
 * 姓/名・よみ姓/よみ名・複数値配列は任意（省略時はフロント旧実装との後方互換）。
 * emails/phones/addresses が非空ならそれらで子テーブルを作り直し、空なら flat の主値のみ反映。
 */
export type ContactInput = { id: number | null, display_name: string, 
/**
 * ラベル付き複数メール（非空ならこれで確定）。
 */
emails: Array<ContactValueInput>, 
/**
 * ラベル付き複数電話。
 */
phones: Array<ContactValueInput>, 
/**
 * ラベル付き複数住所（構造化）。
 */
addresses: Array<ContactAddressInput>, 
/**
 * タグ（グループ/ラベル）名。指定時はメンバーシップをこの集合に一致させる。
 */
tags: Array<string>, 
/**
 * 姓（構造化名）。
 */
family_name: string | null, 
/**
 * 名。
 */
given_name: string | null, 
/**
 * よみ（姓）。
 */
phonetic_family: string | null, 
/**
 * よみ（名）。
 */
phonetic_given: string | null, name_kana: string | null, email: string | null, phone: string | null, organization: string | null, 
/**
 * 役職。
 */
org_title: string | null, 
/**
 * 部署。
 */
org_department: string | null, address: string | null, birthday: string | null, note: string | null, is_favorite: boolean, is_business: boolean, allow_remote_images: boolean, };
