// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * カスタム項目（Google の userDefined）。
 */
export type ContactCustomField = { key: string, value: string, };
