// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactAddress } from "./ContactAddress";
import type { ContactCustomField } from "./ContactCustomField";
import type { ContactDate } from "./ContactDate";
import type { ContactHandle } from "./ContactHandle";
import type { ContactOrganization } from "./ContactOrganization";
import type { ContactRelation } from "./ContactRelation";
import type { ContactUrl } from "./ContactUrl";
import type { ContactValue } from "./ContactValue";

/**
 * 連絡先の中身（編集できる項目のすべて）。一覧/詳細・入力・取り込みの中間表現で共有する。
 *
 * 子テーブル由来の配列は**先頭が主値**（`position = 0`）。一覧（`contact_list`）では
 * 配列とタグは空で返し、詳細（`contact_get`）で充填する。
 */
export type ContactFields = { 
/**
 * 表示名（vCard の FN）。
 */
display_name: string, 
/**
 * 敬称（N の 4 番目 / Google の honorificPrefix）。
 */
name_prefix: string | null, 
/**
 * 姓。
 */
family_name: string | null, 
/**
 * ミドルネーム。
 */
middle_name: string | null, 
/**
 * 名。
 */
given_name: string | null, 
/**
 * 接尾辞（N の 5 番目 / Google の honorificSuffix）。
 */
name_suffix: string | null, 
/**
 * よみ（姓）。
 */
phonetic_family: string | null, 
/**
 * よみ（ミドル）。
 */
phonetic_middle: string | null, 
/**
 * よみ（名）。
 */
phonetic_given: string | null, 
/**
 * ニックネーム。
 */
nickname: string | null, 
/**
 * 旧姓（iCloud のみ）。
 */
maiden_name: string | null, 
/**
 * 誕生日（`YYYY-MM-DD` / 年なし `--MM-DD`）。
 */
birthday: string | null, note: string | null, 
/**
 * 会社として表示する（iCloud の X-ABShowAs:COMPANY）。
 */
show_as_company: boolean, 
/**
 * お気に入り（Google の「スター付き」と同期）。
 */
is_favorite: boolean, 
/**
 * 取引先の手動フラグ（Rondine 固有。docs/FILTERING.md）。
 */
is_business: boolean, 
/**
 * この相手からのメールで外部画像を許可（Rondine 固有。docs/MAIL_SECURITY.md）。
 */
allow_remote_images: boolean, organizations: Array<ContactOrganization>, emails: Array<ContactValue>, phones: Array<ContactValue>, addresses: Array<ContactAddress>, urls: Array<ContactUrl>, dates: Array<ContactDate>, relations: Array<ContactRelation>, handles: Array<ContactHandle>, custom_fields: Array<ContactCustomField>, 
/**
 * タグ（メールと共通の tags。Google のラベル / vCard の CATEGORIES）。
 */
tags: Array<string>, };
