// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactLinkState } from "./ContactLinkState";
import type { ContactProvider } from "./ContactProvider";

/**
 * つながり（どのサービスのどのアカウントと同期しているか）。一覧・詳細のアイコン用。
 */
export type ContactLink = { provider: ContactProvider, 
/**
 * 連携アカウントの ID（Google は `google_accounts.id`）。
 */
account_id: number, 
/**
 * 連携アカウントのメールアドレス（同じサービスに複数アカウントがありうるため添える）。
 */
account_email: string | null, 
/**
 * 連携アカウントの名前（設定のカードの呼び名。付けていなければアドレス）。印の表示に使う。
 */
account_label: string | null, 
/**
 * 連携アカウントが解除中（つながりは残るが同期されない。再接続すると戻る）。
 */
disconnected: boolean, 
/**
 * つながりの状態（作成待ち・削除待ちは次の同期で送る）。
 */
state: ContactLinkState, };
