// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactLink } from "./ContactLink";

/**
 * 連絡先一覧の 1 行（一覧に出す分だけ）。
 *
 * 一覧は数千件になるので、[`ContactSummary`] の全項目（ほとんど空）を IPC に載せると、
 * JSON の組み立てと読み込みだけで画面が止まる。開いたら [`ContactSummary`] を取り直す。
 */
export type ContactListItem = { id: number, display_name: string, 
/**
 * 主メール（一覧の 2 行目。会社名が無いとき）。
 */
primary_email: string | null, 
/**
 * 主の会社名（一覧の 2 行目）。
 */
primary_organization: string | null, is_favorite: boolean, 
/**
 * 論理削除（ゴミ箱）の日時（UTC 文字列）。非 null＝削除済み。
 */
deleted_at: string | null, 
/**
 * つながっているサービス（同期先の印と、同期先での絞り込みに使う）。
 */
links: Array<ContactLink>, };
