// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ラベル付きの構造化住所。
 */
export type ContactAddress = { id: number, label: string | null, postal: string | null, region: string | null, city: string | null, street: string | null, extended: string | null, country: string | null, is_primary: boolean, };
