// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HandleKind } from "./HandleKind";

/**
 * チャット・SNS のハンドル。
 */
export type ContactHandle = { kind: HandleKind, 
/**
 * サービス名（Skype / LINE / Twitter など）。
 */
service: string | null, 
/**
 * ユーザー名またはプロフィールの URL。
 */
value: string, label: string | null, };
