// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 構造化住所の入力。
 */
export type ContactAddressInput = { label: string | null, postal: string | null, region: string | null, city: string | null, street: string | null, extended: string | null, country: string | null, };
