// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ラベル付きの URL。
 */
export type ContactUrl = { label: string | null, value: string, };
