// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ラベル付きの値（メール・電話）。並び順の先頭が主値。
 */
export type ContactValue = { 
/**
 * 見出し（自宅/職場/携帯/FAX/代表/カスタム名）。
 */
label: string | null, value: string, 
/**
 * 複数名で共有する会社の代表値（info@… / 代表電話 / 代表FAX 等）。Rondine 固有の印で、
 * 人単位の重複判定の手掛かりから除外する。どのサービスにも送らない。
 */
is_shared: boolean, };
