// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 連絡先グループ（所属件数つき。編集 UI は後続）。
 */
export type ContactGroupSummary = { id: number, name: string, color: string | null, 
/**
 * 所属している連絡先の件数。
 */
count: number, };
