// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactAddress } from "./ContactAddress";
import type { ContactValue } from "./ContactValue";

/**
 * 連絡先（住所録）。一覧・詳細・編集で共通に使う（連絡先はメールほど大量でないため軽量/詳細を分けない）。
 * メール/電話/住所は子テーブル由来のラベル付き複数値（arrays）。flat な email/phone/address は
 * 主(primary)値の写しで、一覧表示や後方互換のために保持する。
 */
export type ContactSummary = { id: number, display_name: string, 
/**
 * 姓（構造化名。表示名とは別）。
 */
family_name: string | null, 
/**
 * 名。
 */
given_name: string | null, 
/**
 * よみ（姓）。
 */
phonetic_family: string | null, 
/**
 * よみ（名）。
 */
phonetic_given: string | null, 
/**
 * 読み（並び替え用。よみ姓＋よみ名の結合など）。
 */
name_kana: string | null, 
/**
 * 主メールアドレス（primary の写し）。
 */
email: string | null, phone: string | null, organization: string | null, 
/**
 * 役職。
 */
org_title: string | null, 
/**
 * 部署。
 */
org_department: string | null, 
/**
 * 主住所の整形文字列（primary の写し。一覧用）。
 */
address: string | null, 
/**
 * 誕生日（YYYY-MM-DD 等の文字列。ホーム/ウィジェット通知用）。
 */
birthday: string | null, note: string | null, 
/**
 * お気に入り（先頭に固定表示）。
 */
is_favorite: boolean, 
/**
 * 取引先の手動フラグ（docs/FILTERING.md）。
 */
is_business: boolean, 
/**
 * この相手からのメールで外部画像を許可（docs/MAIL_SECURITY.md）。
 */
allow_remote_images: boolean, 
/**
 * ラベル付き複数メール（詳細取得時のみ充填。一覧では空）。
 */
emails: Array<ContactValue>, 
/**
 * ラベル付き複数電話（同上）。
 */
phones: Array<ContactValue>, 
/**
 * ラベル付き複数住所（同上）。
 */
addresses: Array<ContactAddress>, };
