// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ラベル付き値の入力（メール・電話）。
 */
export type ContactValueInput = { label: string | null, value: string, };
