// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ラベル付きの値（メール・電話）。Apple/Google のラベル付き複数値に対応。
 */
export type ContactValue = { id: number, 
/**
 * 見出し（自宅/職場/携帯/カスタム＝会社名など）。
 */
label: string | null, value: string, is_primary: boolean, };
