// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 連絡先（住所録）。一覧・詳細・編集で共通に使う（連絡先はメールほど大量でないため軽量/詳細を分けない）。
 */
export type ContactSummary = { id: number, display_name: string, 
/**
 * 読み（並び替え用）。
 */
name_kana: string | null, 
/**
 * 主メールアドレス。
 */
email: string | null, phone: string | null, organization: string | null, address: string | null, 
/**
 * 誕生日（YYYY-MM-DD 等の文字列。ホーム/ウィジェット通知用）。
 */
birthday: string | null, note: string | null, 
/**
 * お気に入り（先頭に固定表示）。
 */
is_favorite: boolean, 
/**
 * 取引先の手動フラグ（docs/FILTERING.md）。
 */
is_business: boolean, 
/**
 * この相手からのメールで外部画像を許可（docs/MAIL_SECURITY.md）。
 */
allow_remote_images: boolean, };
