// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactProvider } from "./ContactProvider";

/**
 * つながり（どのサービスのどのアカウントと同期しているか）。一覧・詳細のアイコン用。
 */
export type ContactLink = { provider: ContactProvider, 
/**
 * 連携アカウントの ID（Google は `google_accounts.id`）。
 */
account_id: number, 
/**
 * 連携アカウントのメールアドレス（同じサービスに複数アカウントがありうるため添える）。
 */
account_email: string | null, 
/**
 * 連携アカウントが解除中（つながりは残るが同期されない。再接続すると戻る）。
 */
disconnected: boolean, };
