// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 重複候補の一致（新規登録前チェック・編集中の赤字警告・メールからの＋追加で使う）。
 * 入力（メール/電話/氏名）と一致した既存連絡先を、どの項目で一致したか付きで返す。
 * 共有指定された値は手掛かりから除外済み。
 */
export type ContactMatch = { id: number, display_name: string, organization: string | null, 
/**
 * 既存連絡先の主メール（表示用）。
 */
email: string | null, 
/**
 * 既存連絡先の主電話（表示用）。
 */
phone: string | null, 
/**
 * 入力メールのうち一致したもの（呼び出し元が渡した値のまま）。フロントの赤字判定に使う。
 */
matched_emails: Array<string>, 
/**
 * 入力電話/FAX のうち一致したもの（呼び出し元が渡した値のまま）。
 */
matched_phones: Array<string>, 
/**
 * 表示名が一致したか。
 */
matched_name: boolean, };
