// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 記念日などの日付（誕生日は本体の `birthday`）。`YYYY-MM-DD` か年なしの `--MM-DD`。
 */
export type ContactDate = { label: string | null, date: string, };
