// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * データ保存先（mail.db と添付キャッシュのフォルダ）と使用量。
 * バイト数は f64（TS の number）で大きな値も安全に渡す。
 */
export type DataLocation = { 
/**
 * 現在のデータフォルダ（絶対パス）。
 */
dir: string, 
/**
 * 既定の場所を使っているか（移動していない）。
 */
is_default: boolean, 
/**
 * mail.db（＋WAL/SHM）の合計バイト。
 */
db_bytes: number, 
/**
 * 添付キャッシュの合計バイト。
 */
attachments_bytes: number, };
