// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * データベースの状態（スキーマバージョン・パス）。
 */
export type DbInfo = { schema_version: number, path: string, };
