// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 「別人」として記録した 2 人（重複の整理で同じ組にしない。取り消しの入口用）。
 */
export type DistinctPair = { a_id: number, a_name: string, b_id: number, b_name: string, };
