// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 下書きの再編集用の内容（drafts フォルダの 1 件を作成画面へ読み戻す）。
 */
export type DraftContent = { 
/**
 * 下書きの emails.id（更新・削除のキー）。
 */
id: number, account_id: number, 
/**
 * 宛先（カンマ区切り文字列。作成画面の入力表記に合わせる）。
 */
to: string, cc: string, 
/**
 * 手入力した Bcc（カンマ区切り文字列。無ければ空）。
 */
bcc: string, subject: string, 
/**
 * 保存した本文（署名・引用込みの全文）。作成画面ではこれをそのまま編集する。
 */
body: string, 
/**
 * 返信元の Message-ID（返信の下書きのみ。無ければ None）。
 */
in_reply_to: string | null, 
/**
 * 返信元メール（in_reply_to で紐づく元メール）の emails.id。作成画面で右ペインに
 * 元メールを並べて表示するのに使う（返信時と同じ 2 分割）。見つからなければ None。
 */
source_id: number | null, };
