// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 下書きの自動保存の入力（フロントから受け取る。docs/COMPOSE.md）。
 * 書きかけの内容をローカルの drafts フォルダへ保存する（IMAP へは上げない）。
 * `draft_id` があれば既存の下書きを更新、無ければ新規作成して id を返す。
 */
export type DraftInput = { 
/**
 * 更新対象の下書き（emails.id）。新規保存なら None。
 */
draft_id: number | null, 
/**
 * 差出人アカウント（accounts.id）。
 */
account_id: number, to: Array<string>, cc: Array<string>, 
/**
 * ユーザーが手入力した Bcc（自動設定はしない）。再編集で復元し、送信時は宛先に使う。
 */
bcc: Array<string>, subject: string, 
/**
 * プレーン本文（署名・引用込みの、その時点の全文）。
 */
body: string, 
/**
 * 返信元の Message-ID（返信の下書きのみ。新規/転送は None）。再編集・再送信の
 * スレッド化に使う。
 */
in_reply_to: string | null, };
