// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 下書きの自動保存の入力（フロントから受け取る。docs/COMPOSE.md）。
 * 書きかけの内容をローカルの drafts フォルダへ保存する（IMAP へは上げない）。
 * `draft_id` があれば既存の下書きを更新、無ければ新規作成して id を返す。
 */
export type DraftInput = { 
/**
 * 更新対象の下書き（emails.id）。新規保存なら None。
 */
draft_id: number | null, 
/**
 * 差出人アカウント（accounts.id）。
 */
account_id: number, to: Array<string>, cc: Array<string>, subject: string, 
/**
 * プレーン本文（署名・引用込みの、その時点の全文）。
 */
body: string, };
