// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 下書きに紐づく添付 1 件（作成画面 ⇄ 下書きの往復で使う）。
 * 手元にファイルがあるものは `path`、転送で引き継いだが本体が未取得のものは
 * `source_attachment_id` を持つ（送信時にサーバーから取り直してから同梱する）。
 */
export type DraftAttachment = { 
/**
 * ローカルの実ファイル（選択/退避したファイル、または取得済みの添付）。未取得なら None。
 */
path: string | null, 
/**
 * 転送元の attachments.id（未取得のものを取り直すキー）。手元のファイルなら None。
 */
source_attachment_id: number | null, 
/**
 * 表示名。
 */
filename: string, 
/**
 * バイト数（合計サイズの表示・上限判定用。添付は 25MB 上限なので i32 で足りる）。
 */
size: number, };
