// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactSummary } from "./ContactSummary";

/**
 * 重複候補のグループ（整理 UI 用）。同一の正規化表示名でまとめる。
 */
export type DuplicateGroup = { 
/**
 * グループの見出し（代表の表示名）。
 */
label: string, 
/**
 * 重複候補の連絡先（2 件以上）。
 */
contacts: Array<ContactSummary>, };
