// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 予定の作成・更新入力（フロントから受け取る）。`id` が None なら新規作成。
 */
export type EventInput = { id: number | null, title: string, description: string | null, location: string | null, start_at: string, end_at: string | null, all_day: boolean, color: string | null, 
/**
 * 繰り返し（RRULE。後続段階。UI は未接続だが前方互換で受ける）。
 */
recurrence: string | null, 
/**
 * 開始何分前に通知（後続段階）。
 */
reminder_minutes: number | null, 
/**
 * メールから作成した場合の紐付け（後続段階）。
 */
related_email_id: number | null, };
