// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * カレンダー予定（一覧・詳細共通）。docs/DATABASE_SCHEMA.md（events）。
 * 日時は端末ローカルの素の ISO8601 文字列（終日='YYYY-MM-DD' / 時間指定='YYYY-MM-DDTHH:MM'）。
 */
export type EventSummary = { id: number, title: string, description: string | null, location: string | null, 
/**
 * 開始。終日は日付のみ、時間指定は 'YYYY-MM-DDTHH:MM'。
 */
start_at: string, 
/**
 * 終了（任意）。終日の複数日は最終日を含む。
 */
end_at: string | null, all_day: boolean, 
/**
 * 色分け（任意。CSS 色 or パレットキー）。
 */
color: string | null, 
/**
 * 繰り返し（RRULE。後続段階）。
 */
recurrence: string | null, 
/**
 * 開始何分前に通知（後続段階）。
 */
reminder_minutes: number | null, 
/**
 * メールから作成した場合の紐付け（後続段階）。
 */
related_email_id: number | null, 
/**
 * 論理削除（ゴミ箱）の日時（UTC 文字列）。非 null＝削除済み。
 */
deleted_at: string | null, };
