// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 予定の参加者（ゲスト）。docs/DATABASE_SCHEMA.md（event_attendees）。
 */
export type EventAttendee = { id: number, 
/**
 * 住所録と紐付く場合（任意）。
 */
contact_id: number | null, email: string | null, name: string | null, 
/**
 * 'accepted' | 'declined' | 'tentative' | 'none'。
 */
response: string, };
