// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * エビクション（添付バイトの追い出し）結果。
 */
export type EvictionReport = { 
/**
 * 追い出した添付の件数。
 */
evicted: number, 
/**
 * 解放したバイト数。
 */
freed_bytes: number, };
