// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OAuth クライアント資格情報の設定状況（Client ID の有無を UI に伝える。値は返さない）。
 */
export type GcalCredentialsStatus = { 
/**
 * Client ID / Secret の両方が保存済みなら true。
 */
configured: boolean, 
/**
 * 保存済みの Client ID（末尾のみ表示用。未設定なら None）。
 */
client_id_hint: string | null, };
