// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Google カレンダー同期の結果サマリ（docs/CALENDAR_SYNC.md）。
 */
export type GcalSyncResult = { 
/**
 * Google から取り込み（新規＋更新）した予定数。
 */
pulled: number, 
/**
 * Google へ送信（新規＋更新）した予定数。
 */
pushed: number, 
/**
 * 取り込みで削除扱いにした予定数（Google 側で削除された分）。
 */
deleted_in: number, 
/**
 * Google 側で削除した予定数（ローカルで削除した分）。
 */
deleted_out: number, 
/**
 * 同期したカレンダー数。
 */
calendars: number, };
