// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Google 連絡先同期（push → pull）の結果サマリ。
 *
 * 取り込んだ連絡先のうち**まだ住所録の誰とも結び付いていない**ものは `contact_identities`
 * （台帳）に留まる。`unlinked` はその件数＝「住所録へ反映」（照合）の対象数。
 */
export type GcontactsSyncResult = { 
/**
 * Google から取り込んだ（新規＋更新）件数。
 */
pulled: number, 
/**
 * Google へ送った（作成＋更新）件数。
 */
pushed: number, 
/**
 * Google 側で削除された印を付けた件数。
 */
deleted_in: number, 
/**
 * ローカルの削除を Google 側へ反映した件数。
 */
deleted_out: number, 
/**
 * 連絡先として成立せず飛ばした件数（名前もメールも電話も無い等）。
 */
skipped: number, 
/**
 * etag 不一致で送れなかった件数（Google 側が先に更新されていた。次回に持ち越す）。
 */
conflicts: number, 
/**
 * 未照合の件数（「住所録へ反映」の対象数）。
 */
unlinked: number, 
/**
 * 1 回の同期で送る上限・Google の上限（429）で送り切れず、次の同期へ回した件数。
 */
deferred: number, };
