// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 照合フェーズ（台帳 → 住所録）の結果サマリ。プレビューと適用で同じ形を返す。
 *
 * `ambiguous` は「似た相手が居たが自動で決めきれず、新規として起こした」件数。
 * 判定は重複検出と同じ物差しなので、この分はそのまま「重複整理」に候補として出る。
 */
export type GcontactsMatchResult = { 
/**
 * 既存の連絡先に紐付けた（紐付ける）件数。
 */
linked: number, 
/**
 * 新規として住所録に起こした（起こす）件数。
 */
created: number, 
/**
 * `created` のうち、似た相手が居て人の確認に回る件数。
 */
ambiguous: number, };
