// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Google 連絡先取り込みの結果サマリ。
 *
 * 取り込みは `contact_identities`（台帳）までで、住所録には反映しない。`unlinked` は
 * 「取り込んだが、まだローカルの誰とも結び付いていない」件数＝照合フェーズの対象数。
 */
export type GcontactsSyncResult = { 
/**
 * Google から取り込んだ（新規＋更新）件数。
 */
pulled: number, 
/**
 * Google 側で削除された印を付けた件数。
 */
deleted_in: number, 
/**
 * 連絡先として成立せず飛ばした件数（名前もメールも電話も無い等）。
 */
skipped: number, 
/**
 * 未照合の件数（照合フェーズの対象数）。
 */
unlinked: number, };
