// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 1 つの Google アカウントが兼ねる同期サービス（カードのスイッチ 1 つずつ）。
 */
export type GoogleService = "calendar" | "contacts";
