// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 連携した Google アカウント。カレンダーと連絡先で 1 件を共有し、サービスごとに
 * 有効フラグと最終同期時刻だけを分けて持つ。資格情報（refresh_token）は keyring に
 * 保存し、ここにはメタ情報のみ持つ（docs/CALENDAR_SYNC.md）。
 */
export type GoogleAccount = { id: number, 
/**
 * 連携した Google アカウントのメールアドレス。
 */
email: string, 
/**
 * カレンダー同期を有効にしているか。
 */
sync_calendar: boolean, 
/**
 * 連絡先同期を有効にしているか。
 */
sync_contacts: boolean, 
/**
 * 新しく作る連絡先の同期先に、既定でこのアカウントを入れるか（既定 false。新規作成の画面の
 * 最初のチェックにだけ効く。どこにもつながっていない連絡先を勝手に作ることはしない）。
 */
push_new_contacts: boolean, 
/**
 * カレンダーの最終同期時刻（UTC 文字列）。未同期なら None。
 */
last_calendar_sync_at: string | null, 
/**
 * 連絡先の最終同期時刻（UTC 文字列）。未同期なら None。
 */
last_contacts_sync_at: string | null, 
/**
 * 解除中になった時刻（UTC 文字列）。None＝連携中。解除中は同期せず、記録は残す。
 */
disconnected_at: string | null, };
