// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GcalSyncResult } from "./GcalSyncResult";
import type { GcontactsMatchResult } from "./GcontactsMatchResult";
import type { GcontactsSyncResult } from "./GcontactsSyncResult";

/**
 * Google アカウント 1 件の同期（「今すぐ同期」・自動同期）の結果。
 *
 * カレンダーと連絡先は独立に進めるので、成否を別々に持つ。同期しなかった側は結果もエラーも None。
 */
export type GoogleSyncResult = { calendar: GcalSyncResult | null, calendar_error: string | null, contacts: GcontactsSyncResult | null, 
/**
 * 取り込みに続けて住所録へ反映した結果（つないだ／新規／重複整理の候補）。
 */
matched: GcontactsMatchResult | null, contacts_error: string | null, };
