// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Google 連携の解除の結果。
 */
export type GoogleDisconnectResult = { 
/**
 * 「完全に解除」で Google 側の許可を取り消せなかったときの理由（解除そのものは済んでいる）。
 * 一時的な解除・取り消せたときは None。
 */
revoke_error: string | null, };
