// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 連携した Google（カレンダー）アカウント。資格情報（refresh_token）は keyring に保存し、
 * ここにはメタ情報のみ持つ（docs/CALENDAR_SYNC.md）。
 */
export type GoogleAccount = { id: number, 
/**
 * 連携した Google アカウントのメールアドレス。
 */
email: string, 
/**
 * 最終同期時刻（UTC 文字列）。未同期なら None。
 */
last_sync_at: string | null, };
