// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * グリーン／警告ドメインの 1 件（管理タブ用）。docs/GREEN_DOMAINS.md。
 */
export type GreenDomainEntry = { domain: string, 
/**
 * "green"（認定）| "warning"（除外）。
 */
kind: string, 
/**
 * 住所録由来（自動グリーンの対象。フリーメール除く）か。
 */
auto: boolean, 
/**
 * このドメインを持つ連絡先の件数（参考）。
 */
contact_count: number, 
/**
 * 手動登録時のメモ（任意）。
 */
note: string | null, };
