// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ホームのアカウント別バッジ用: inbox の未読数をカテゴリ別（all/green/known/vip）に数えたもの。
 */
export type HomeUnreadCounts = { account_id: number, all: number, green: number, known: number, vip: number, };
