// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ICS 取り込みの結果（docs/IMPORT_EXPORT.md）。
 */
export type IcsImportReport = { 
/**
 * ファイル内の VEVENT 総数。
 */
total: number, 
/**
 * 追加した件数。
 */
imported: number, 
/**
 * 成立せず飛ばした件数（開始日時なし等）。
 */
skipped: number, };
