// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 連絡先インポートの結果（vCard 取り込み。docs/IMPORT_EXPORT.md）。
 */
export type ImportReport = { 
/**
 * ファイル内の vCard 総数。
 */
total: number, 
/**
 * 新規追加した件数。
 */
imported: number, 
/**
 * 既存（UID かメール一致）を更新した件数。
 */
updated: number, 
/**
 * 連絡先として成立せず飛ばした件数（名前・メール・電話いずれも無い等）。
 */
skipped: number, };
