// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * メール一覧表示用（軽量）。
 */
export type MailSummary = { id: number, subject: string | null, from_address: string | null, date: string | null, preview: string, is_read: boolean, has_attachments: boolean, is_starred: boolean, is_bookmarked: boolean, 
/**
 * 付与されているタグの ID 群（表示・絞り込み用）。
 */
tag_ids: Array<number>, };
