// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * メール一覧表示用（軽量）。
 */
export type MailSummary = { id: number, 
/**
 * 所属アカウント ID（「全て」表示で、どのアカウントのメールか識別する）。
 */
account_id: number, subject: string | null, from_address: string | null, 
/**
 * 差出人の表示名（ヘッダ From の名前部。無ければ None）。
 */
from_name: string | null, 
/**
 * 宛先（送信済・下書きフォルダで「To」を表示するのに使う）。
 */
to_addresses: string | null, 
/**
 * 宛先（先頭）の表示名（ヘッダ To の名前部。無ければ None）。
 */
to_name: string | null, date: string | null, preview: string, is_read: boolean, 
/**
 * 添付の有無（旧データ由来のヒント。inline を含む場合がある）。
 */
has_attachments: boolean, 
/**
 * 実ファイルの添付行（kind='attachment'）が手元にあるか。フィルタ用。
 */
has_real_attachments: boolean, is_starred: boolean, is_bookmarked: boolean, 
/**
 * 付与されているタグの ID 群（表示・絞り込み用）。
 */
tag_ids: Array<number>, 
/**
 * 差出人が住所録に登録済み（知り合い）か。フィルタ用。
 */
is_known: boolean, 
/**
 * 差出人が住所録のお気に入り（VIP／Gem）連絡先か。フィルタ用。
 */
is_vip: boolean, 
/**
 * 差出人がグリーン（本人 or 認定ドメイン）か。フィルタ・バッジ用。docs/GREEN_DOMAINS.md。
 */
is_green: boolean, };
