// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * メール詳細（本文表示用）。
 */
export type MailDetail = { id: number, 
/**
 * 元メッセージの Message-ID（返信のスレッド化 In-Reply-To 用。無ければ None）。
 */
message_id: string | null, subject: string | null, from_address: string | null, 
/**
 * 差出人の表示名（住所録から解決。無ければ None）。
 */
from_name: string | null, to_addresses: string | null, 
/**
 * 宛先の表示名（住所録から解決。無ければ None）。
 */
to_name: string | null, date: string | null, clean_body: string | null, body_plain: string | null, 
/**
 * HTML 本文（あれば）。レンダラ側でテキスト＋リンクのみ安全描画する。
 */
body_html: string | null, has_attachments: boolean, 
/**
 * 容量節約のため本文を要約保存に落としてある（clean_body のみ）。全文はサーバー再取得可。
 */
body_compacted: boolean, };
