// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 統合で Google 側から消すことになる連絡先の件数（アカウントごと）。統合の確認画面に出す。
 *
 * 統合すると、同じ Google アカウントにつながった ID は 1 つだけ残し、余りは次の同期で
 * Google 側から削除する（docs/CONTACTS_SYNC.md §3-5）。
 */
export type MergeRemoteDeletion = { 
/**
 * `google_accounts.id`。
 */
account_id: number, 
/**
 * アカウントの名前（設定のカードの呼び名。無ければアドレス）。
 */
account_label: string, 
/**
 * 削除する件数（残す 1 件は含まない）。
 */
count: number, };
