// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactSummary } from "./ContactSummary";
import type { OrgSharedValue } from "./OrgSharedValue";
import type { OrganizationSummary } from "./OrganizationSummary";

/**
 * 組織の詳細（所属連絡先・共有アドレス）。住所録の「組織」タブで表示する。
 */
export type OrganizationDetail = { org: OrganizationSummary, 
/**
 * 所属連絡先（軽量サマリ）。
 */
members: Array<ContactSummary>, 
/**
 * 共有アドレス（値ごとに共有件数つき）。
 */
shared_values: Array<OrgSharedValue>, };
