// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrgAddress } from "./OrgAddress";

/**
 * 会社・組織（所属連絡先の件数つき）。コンボボックスの候補・組織一覧・組織カードに使う。
 * 代表電話/FAX/代表メール/URL/所在地は会社共通の情報で、個人の連絡先ではラベル表示する。
 */
export type OrganizationSummary = { id: number, name: string, name_kana: string | null, note: string | null, 
/**
 * 代表電話番号（フロントで E.164 正準形に整えて保存）。
 */
phone: string | null, 
/**
 * 代表 FAX 番号（同上）。
 */
fax: string | null, 
/**
 * 代表メールアドレス（info@… など）。
 */
email: string | null, 
/**
 * ウェブサイトの URL。
 */
url: string | null, 
/**
 * 所在地（未入力の項目は None）。
 */
address: OrgAddress, 
/**
 * この組織に所属する連絡先の件数（削除済みは除く）。
 */
member_count: number, 
/**
 * 論理削除（ゴミ箱）の日時（UTC 文字列）。非 null＝削除済み。
 */
deleted_at: string | null, };
