// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrgAddress } from "./OrgAddress";

/**
 * 組織カードの作成・更新入力（フロントから受け取る）。`id` が None なら新規作成。
 */
export type OrganizationInput = { id: number | null, name: string, name_kana: string | null, note: string | null, phone: string | null, fax: string | null, email: string | null, url: string | null, address: OrgAddress, };
