// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 組織の所在地（構造化住所）。連絡先の住所と同じ構成で、ラベルは持たない（代表所在地 1 か所）。
 */
export type OrgAddress = { postal: string | null, region: string | null, city: string | null, street: string | null, extended: string | null, country: string | null, };
