// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 組織の整理（カードにする・つなぐ）の下見。確認欄で知らせるために数える。
 */
export type OrgChangeImpact = { 
/**
 * 会社名が変わる・会社が足されるため、次の同期でつながっているサービスへ送り直しになる人数。
 */
resent: number, };
