// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrganizationSummary } from "./OrganizationSummary";

/**
 * 組織名の重複候補グループ（「株式会社◯◯」と「(株)◯◯」など。正規化名で束ねる）。
 * 重複整理画面で 1 つの組織に統一するのに使う。
 */
export type OrgDuplicateGroup = { 
/**
 * 既定の統一名（最多所属→最長→名前順）。
 */
canonical: string, 
/**
 * 同一とみなした組織レコード（2 件以上）。
 */
organizations: Array<OrganizationSummary>, };
