// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrgLinkCandidate } from "./OrgLinkCandidate";
import type { OrganizationSummary } from "./OrganizationSummary";

/**
 * 組織カード 1 枚ぶんの「つながっていない人」の候補。
 */
export type OrgLinkSuggestion = { org: OrganizationSummary, candidates: Array<OrgLinkCandidate>, };
