// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactSummary } from "./ContactSummary";

/**
 * 組織カードにつながっていないが、同じ組織らしい人（理由つき）。
 */
export type OrgLinkCandidate = { 
/**
 * 候補の連絡先（一覧用の軽い形）。
 */
contact: ContactSummary, 
/**
 * 会社名が一致した（正規化後）ときの、その人の会社名。
 */
matched_name: string | null, 
/**
 * メールのドメインが一致したときの、そのドメイン。
 */
matched_domain: string | null, };
