// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 組織の共有アドレス（会社の代表 info@ / 代表電話 / 代表FAX 等）。
 * 「組織 ＋ 値 ＋ 共有件数（何名が共有指定しているか）」を組織詳細で表示する。
 */
export type OrgSharedValue = { 
/**
 * 種別: "email" | "phone"（FAX は label で区別）。
 */
kind: string, label: string | null, value: string, 
/**
 * この組織でこの値を共有指定している連絡先の件数。
 */
count: number, };
