// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 郵便番号表から引いた住所 1 件（日本）。住所欄の自動入力に使う。
 */
export type PostalAddress = { 
/**
 * 郵便番号（「NNN-NNNN」）。
 */
postal: string, 
/**
 * 都道府県。
 */
region: string, 
/**
 * 市区町村。
 */
city: string, 
/**
 * 町域（市区町村の既定の番号なら空）。
 */
town: string, };
