// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebuildAction } from "./RebuildAction";

/**
 * 再構築の実行計画。記録されているデータ形式バージョンと現行値の比較結果。
 */
export type RebuildPlan = { action: RebuildAction, 
/**
 * アカウントに記録された取り込み形式バージョン（0=形式不明）と現行値。
 */
ingest_stored: number, ingest_current: number, 
/**
 * アカウントに記録された解析バージョンと現行値。
 */
parse_stored: number, parse_current: number, };
