// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 再構築で実行する処理。データ形式バージョンの比較で決まる（services/dataver.rs）。
 */
export type RebuildAction = "resync" | "reprocess";
