// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * メール作成の宛先オートコンプリート候補（docs/RECIPIENT_AUTOCOMPLETE.md）。
 * 住所録（source="contact"）と過去のやり取り相手（source="history"）を統合し、
 * メールアドレスで重複排除して返す。
 */
export type RecipientSuggestion = { 
/**
 * 表示用メールアドレス。
 */
email: string, 
/**
 * 表示名（連絡先名、またはヘッダ "Name <addr>" から抽出。無ければ None）。
 */
name: string | null, 
/**
 * 候補の出所: "contact"（住所録）| "history"（送受信履歴）。
 */
source: string, 
/**
 * 住所録のお気に入り（並びで優先）。履歴由来は false。
 */
is_favorite: boolean, 
/**
 * 住所録由来なら連絡先 ID（詳細展開用）。履歴由来は None。
 */
contact_id: number | null, };
