// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 明示許可して取得したリモート画像（サニタイズ済み）。docs/MAIL_SECURITY.md §1.1。
 */
export type RemoteImage = { 
/**
 * 元の（正規化済み）画像 URL。フロントの src マッチに使う。
 */
url: string, 
/**
 * 表示用に再エンコード（＝デコーダ攻撃・EXIF も無害化）した data URL（image/jpeg）。
 */
data_url: string, };
