// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 保持ポリシー適用（期間ベースの3ティア＋容量上限の保険）の結果。
 */
export type RetentionReport = { 
/**
 * ローカルから削除した添付ファイルの件数（Tier2＋容量保険）。
 */
evicted: number, 
/**
 * 要約保存に落とした本文の件数（Tier3）。
 */
compacted: number, 
/**
 * 解放したバイト数（添付＋本文の概算）。
 */
freed_bytes: number, };
