// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * メール送信の入力（フロントから受け取る。docs/COMPOSE.md）。
 * 本文はプレーンで作成し、送信時に HTML を自動生成して plain+HTML を同梱する。
 */
export type SendInput = { 
/**
 * 差出人アカウント（accounts.id）。
 */
account_id: number, to: Array<string>, cc: Array<string>, bcc: Array<string>, subject: string, 
/**
 * 新規に書いた本文（プレーン。署名込み・引用は含まない）。HTML は送信時に自動生成する。
 */
body: string, 
/**
 * 返信/転送で本文末に足す「プレーン引用」（属性行＋`>` 引用）。新規なら None。
 * プレーン本文はこれを body の後ろに連結して送る。
 */
quoted_plain: string | null, 
/**
 * 返信/転送で HTML 本文末に足す「HTML 引用」（属性行＋オリジナル HTML を blockquote で
 * そのまま引用。フロントでサニタイズ済み）。指定時は HTML 本文にこれを使う（オリジナルを
 * 再構築せず丸ごと引用＝崩れない）。元メールが HTML を持たない/新規なら None。
 */
quoted_html: string | null, 
/**
 * 返信元の Message-ID（スレッド化用。新規なら None）。
 */
in_reply_to: string | null, 
/**
 * References チェーン（祖先 Message-ID を空白区切り・古い順。相手メーラーで正しく
 * スレッド表示させるため。返信時は「元メールの References ＋ 元メールの Message-ID」。
 * docs/THREADING.md）。
 */
references: string | null, 
/**
 * 添付するローカルファイルのパス配列（送信時に読み込み MIME に同梱）。空なら添付なし。
 */
attachments: Array<string>, };
