// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * メール送信の入力（フロントから受け取る。docs/COMPOSE.md）。
 * 本文はプレーンで作成し、送信時に HTML を自動生成して plain+HTML を同梱する。
 */
export type SendInput = { 
/**
 * 差出人アカウント（accounts.id）。
 */
account_id: number, to: Array<string>, cc: Array<string>, bcc: Array<string>, subject: string, 
/**
 * プレーン本文（作成はプレーン。HTML は送信時に自動生成）。
 */
body: string, 
/**
 * 返信元の Message-ID（スレッド化用。新規なら None）。
 */
in_reply_to: string | null, };
