// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * メールサーバーアカウント設定（接続＋ログイン）。再利用・紐づけ用。
 */
export type ServerAccountSummary = { id: number, name: string | null, imap_host: string, imap_port: number, smtp_host: string, smtp_port: number, username: string, };
