// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 署名（差出人ごとに使い回せる本文）。
 */
export type SignatureSummary = { id: number, name: string, body: string, };
