// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 迷惑メール判定のユーザー設定（docs/SPAM.md §9）。既定値は spam モジュールの定数。
 */
export type SpamSettings = { 
/**
 * 迷惑判定の有効/無効（§9.1 spam.enabled）。
 */
enabled: boolean, 
/**
 * uncertain 帯の下限 τ_low（§8.1）。
 */
threshold_low: number, 
/**
 * junk 隔離の τ_high（§8.1）。
 */
threshold_high: number, };
