// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 迷惑差出人として登録済みだが、信頼シグナル（住所録/グリーン）と矛盾する差出人。
 * ユーザーへ注意喚起する情報リスト用（docs/SPAM.md）。
 */
export type SpamSenderConflict = { 
/**
 * 正規化済みの差出人アドレス。
 */
address: string, 
/**
 * 住所録の表示名（連絡先の場合。無ければ null）。
 */
display_name: string | null, 
/**
 * 矛盾の理由: "contact" | "green" | "contact_green"。
 */
reason: string, };
