// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 迷惑メール判定の結果（docs/SPAM.md §7.5）。
 */
export type SpamVerdict = { 
/**
 * 0..1 の spam スコア。
 */
score: number, 
/**
 * 3 バンド分類（§8.1）: "clean" | "uncertain" | "junk"。
 */
band: string, 
/**
 * spam 寄りに効いた素性トークン（根拠表示用。§8.4）。
 */
top_tokens: Array<string>, };
