// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * アカウントのローカル保存容量（添付キャッシュの使用量と上限）。
 * バイト数は f64（TS の number）で扱い、2GB 超でも安全に渡す。
 */
export type StorageInfo = { 
/**
 * ダウンロード済み添付の合計バイト。
 */
used_bytes: number, 
/**
 * 上限バイト。
 */
limit_bytes: number, };
