// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * まとめて統合する 1 組（確実な重複。下見の一覧用）。
 */
export type SureMergeGroup = { 
/**
 * 残す連絡先。
 */
keep_id: number, display_name: string, 
/**
 * 組の件数（残す 1 件を含む）。
 */
count: number, 
/**
 * 見分けるための主なメール・電話（組の中で同じ）。
 */
email: string | null, phone: string | null, };
