// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 確実な重複をまとめて統合した結果。
 */
export type SureMergeResult = { 
/**
 * まとめた組の数（＝残った連絡先の数）。
 */
groups: number, 
/**
 * 消えた（残す側へまとめた）連絡先の数。
 */
merged: number, 
/**
 * Google 側から消すために削除待ちにした件数（次の同期で送る）。
 */
remote_deletions: number, };
