// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeRemoteDeletion } from "./MergeRemoteDeletion";
import type { SureMergeGroup } from "./SureMergeGroup";

/**
 * 確実な重複をまとめて統合したらどうなるか（読むだけ）。
 */
export type SureMergePreview = { groups: Array<SureMergeGroup>, 
/**
 * 組に入っている連絡先の数（統合後は組の数になる）。
 */
contacts: number, 
/**
 * Google 側から消すことになる件数（アカウントごと）。
 */
remote_deletions: Array<MergeRemoteDeletion>, };
