// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 同期の進捗（Tauri イベント "sync:progress" のペイロード）。
 * フォルダごとに current/total を通知する（total は取得予定件数の目安）。
 */
export type SyncProgress = { 
/**
 * 'inbox' | 'sent' | 'drafts' | 'trash' | 'spam'。
 */
folder: string, 
/**
 * これまでに取得した件数。
 */
current: number, 
/**
 * このフォルダで取得予定の件数（目安）。
 */
total: number, };
