// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 同期結果。
 */
export type SyncResult = { fetched: number, stored: number, 
/**
 * 既存メールに uid/添付メタを埋め戻した件数（点検つき再取り込み時に意味を持つ）。
 */
backfilled: number, };
