// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 新着が一覧に出せる状態になったこと（Tauri イベント "sync:listed" のペイロード）。
 * 本文のダウンロードを待たずにヘッダだけ DB へ入れた時点で発火する（docs/SYNC.md §3.6）。
 */
export type SyncListed = { 
/**
 * 'inbox' | 'sent' | 'drafts' | 'trash' | 'spam'。
 */
folder: string, 
/**
 * 今回一覧に出せるようになった件数（新規に作られた行）。
 */
count: number, };
