// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ユーザー定義タグ（プロジェクト等の任意ラベル。docs/FILTERING.md）。
 */
export type TagSummary = { id: number, name: string, 
/**
 * 表示色（CSS カラー文字列。未設定なら None）。
 */
color: string | null, 
/**
 * 親タグ（フォルダ整理用の階層。ルートは None）。
 */
parent_id: number | null, 
/**
 * 付与されているメール件数。
 */
count: number, };
