// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadMessage } from "./ThreadMessage";
import type { ThreadSummary } from "./ThreadSummary";

/**
 * 会話ビュー（スレッド情報＋時系列のメッセージ）。
 */
export type ThreadView = { thread: ThreadSummary, 
/**
 * 時系列（古い順）のメッセージ。
 */
messages: Array<ThreadMessage>, };
