// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 論理スレッド（アプリが再構築する会話単位。ヘッダスレッドとは独立）。docs/THREADING.md。
 */
export type ThreadSummary = { id: number, 
/**
 * ユーザーが付け直したタイトル（再件名）。未設定なら None。
 */
title: string | null, 
/**
 * 元件名から導いた既定タイトル（最初のメールの件名）。
 */
auto_title: string | null, 
/**
 * このスレッドのメール件数。
 */
message_count: number, 
/**
 * 未読件数。
 */
unread_count: number, 
/**
 * 参加者（差出人アドレスを結合した表示用文字列）。
 */
participants: string | null, 
/**
 * ユーザーがタイトルを付け直したか。
 */
is_user_renamed: boolean, };
