// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * スレッド単位のメール一覧の 1 行（代表メール＋件数）。docs/THREADING.md §5。
 * 代表＝そのフォルダ内で最新のメール（受信箱なら最新の受信。自分の送信は代表にしない）。
 */
export type ThreadListItem = { 
/**
 * 論理スレッド id（未割当の旧データは負値の擬似 id）。
 */
thread_id: number, 
/**
 * 代表メール id（クリックで会話を開く対象＝フォルダ内最新）。
 */
id: number, account_id: number, 
/**
 * 表示件名（再件名 title があればそれ、無ければ代表メールの件名）。
 */
subject: string | null, from_address: string | null, from_name: string | null, to_addresses: string | null, to_name: string | null, 
/**
 * 代表メールの日時。
 */
date: string | null, preview: string, 
/**
 * スレッド（フォルダ内）に未読が無いか。一覧の未読ドット判定に使う。
 */
is_read: boolean, has_real_attachments: boolean, is_starred: boolean, is_bookmarked: boolean, tag_ids: Array<number>, is_known: boolean, is_vip: boolean, is_green: boolean, 
/**
 * スレッド総件数（全フォルダ横断）。「N通」バッジに使う。
 */
message_count: number, 
/**
 * このフォルダの未読件数。
 */
unread_count: number, 
/**
 * 差出人に自分から送ったことがある（返信歴あり）か。フィルタ用。docs/FILTERING.md §2。
 */
is_replied: boolean, 
/**
 * このフォルダに属するスレッド内メール id 群（既読/削除/迷惑の一括操作用）。
 */
email_ids: Array<number>, };
