// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会話ビュー 1 通ぶんのメッセージ（バブル表示用。docs/THREADING.md §5）。
 */
export type ThreadMessage = { id: number, account_id: number, 
/**
 * 返信スレッド化用の Message-ID（無ければ None）。
 */
message_id: string | null, from_address: string | null, 
/**
 * 差出人の表示名（ヘッダ or 住所録から解決。無ければ None）。
 */
from_name: string | null, to_addresses: string | null, subject: string | null, date: string | null, 
/**
 * "out"（自分が送った＝右寄せ）| "in"（相手＝左寄せ）。
 */
direction: string, 
/**
 * 引用・署名を除いた新規本文。
 */
clean_body: string | null, 
/**
 * 引用込みの全文（「引用を表示」で使う）。
 */
body_plain: string | null, 
/**
 * HTML 本文（あれば。展開時に安全描画）。
 */
body_html: string | null, has_attachments: boolean, 
/**
 * 引用が畳まれている（clean より全文が長い）＝「引用を表示」を出すか。
 */
has_quotes: boolean, is_read: boolean, 
/**
 * スター付きか（折りたたみバブルの★バッジ用）。
 */
is_starred: boolean, 
/**
 * 差出人がグリーン（住所録本人 or ドメインがグリーン集合）か。折りたたみバブルの緑バッジ用。
 */
is_green: boolean, 
/**
 * 差出人が住所録のお気に入り（VIP）か。折りたたみバブルの VIP バッジ用。
 */
is_vip: boolean, 
/**
 * 保存フォルダ（'inbox' | 'sent' | ...）。
 */
folder: string | null, 
/**
 * スレッド割当が手動か（'auto' | 'manual'）。
 */
thread_assignment: string, };
