// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 組織カードになっていない会社名（正規化名でまとめたもの）。組織タブの「整理」用。
 */
export type UnlinkedOrgName = { 
/**
 * 代表の表記（最も多く使われている表記）。カードにするときの既定名。
 */
name: string, 
/**
 * 同じ正規化名にまとまった表記の一覧（多い順）。
 */
variants: Array<string>, 
/**
 * この会社名を持つ連絡先の人数（削除済みは除く）。
 */
contact_count: number, };
