// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * vCard の版（連絡先の書き出し）。既定は 3.0（Google 連絡先・iPhone・Outlook が読める）。
 */
export type VcardVersion = "3.0" | "4.0";
